on:
  - push
  - pull_request

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-24.04
    env:
      MIX_ENV: test
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.3.3"
          elixir-version: "1.18.3"
      - name: Install apt packages
        run: sudo apt update && sudo apt install -y libmnl-dev
      - name: Install Nerves bootstrap
        run: mix archive.install --force hex nerves_bootstrap
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get dependencies
        run: mix deps.get --only test
      - name: Run unit tests
        run: mix test

  type_check:
    name: Type Check
    runs-on: ubuntu-24.04
    env:
      MIX_TARGET: gate
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.3.3"
          elixir-version: "1.18.3"
      - name: Install apt packages
        run: sudo apt update && sudo apt install -y libmnl-dev
      - name: Install Nerves bootstrap
        run: mix archive.install --force hex nerves_bootstrap
      - name: Restore Nerves artifacts
        uses: actions/cache@v4
        with:
          path: ~/.nerves/artifacts
          key: nerves-artifacts-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            nerves-artifacts-${{ github.ref }}-${{ github.sha }}
            nerves-artifacts-${{ github.ref }}-
            nerves-artifacts-refs/heads/master-
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create bogus SSH key
        run: mkdir -p ~/.ssh; echo "bogus" > ~/.ssh/id_rsa.pub
      - name: Get dependencies
        run: mix deps.get --only dev
      - name: Restore PLTs
        uses: actions/cache@v4
        with:
          path: _build/${{ env.MIX_TARGET }}_dev/plt
          key: plt-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            plt-${{ github.ref }}-${{ github.sha }}
            plt-${{ github.ref }}-
            plt-refs/heads/master-
      - name: Compile
        run: mix compile
      - name: Run dialyzer
        run: mix dialyzer
